export const EVENTS = [
  {
    id: 0,
    headerTitle: 'Quinta feira, 24 Dezembro, 2023: Inovação e Tendências Tecnológicas',
    position: 1,
    activities: [
      {
        id: 0,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 1,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 2,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 3,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'canceled',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 4,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 5,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
    ],
  },
  {
    id: 1,
    headerTitle: 'Quinta feira, 24 Dezembro, 2023: Inovação e Tendências Tecnológicas',
    position: 2,
    activities: [
      {
        id: 0,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 1,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 2,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 3,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'inProgress',
        inProgress: true,
        date: '09:00 - 10:30 GMT+1',
      },
    ],
  },
]
