import { CalendarBlank, User } from '@phosphor-icons/react/dist/ssr'

export const EVENTS = [
  {
    id: 0,
    headerTitle: 'Quinta feira, 24 Dezembro, 2023: Inovação e Tendências Tecnológicas',
    position: 1,
    activities: [
      {
        id: 0,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 1,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 2,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 3,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'canceled',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 4,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 5,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
    ],
  },
  {
    id: 1,
    headerTitle: 'Quinta feira, 24 Dezembro, 2023: Inovação e Tendências Tecnológicas',
    position: 2,
    activities: [
      {
        id: 0,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 1,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 2,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'accomplished',
        inProgress: false,
        date: '09:00 - 10:30 GMT+1',
      },
      {
        id: 3,
        title: 'Introdução à Inteligência Artificial',
        specialGuest: 'Dr. Maria Silva, CEO da TechGenius',
        state: 'inProgress',
        inProgress: true,
        date: '09:00 - 10:30 GMT+1',
      },
    ],
  },
]

export const EVENTCARDINFORMATION = [
  {
    id: 0,
    urlVideo: 'https://www.youtube.com/embed/oZMH6vbfkFY?si=0fjlR625Ii6GcSFf',
    date: '15 a 17 de Março de 2024',
    Icon: CalendarBlank,
    title: 'Software Engineering Principles',
    details: [
      { id: 0, Icon: User, content: '+37 Participantes' },
      { id: 1, Icon: User, content: '10 Palentrantes' },
      { id: 2, Icon: User, content: '10 Registros' },
      { id: 3, Icon: User, content: '15 patrocinadores' },
    ],
  },
  {
    id: 1,
    urlVideo: 'https://www.youtube.com/embed/oZMH6vbfkFY?si=0fjlR625Ii6GcSFf',
    date: '15 a 17 de Março de 2024',
    Icon: CalendarBlank,
    title: 'Software Engineering Principles',
    details: [
      { id: 0, Icon: User, content: '+37 Participantes' },
      { id: 1, Icon: User, content: '10 Palentrantes' },
      { id: 2, Icon: User, content: '10 Registros' },
      { id: 3, Icon: User, content: '15 patrocinadores' },
    ],
  },
  {
    id: 2,
    urlVideo: 'https://www.youtube.com/embed/oZMH6vbfkFY?si=0fjlR625Ii6GcSFf',
    date: '15 a 17 de Março de 2024',
    Icon: CalendarBlank,
    title: 'Software Engineering Principles',
    details: [
      { id: 0, Icon: User, content: '+37 Participantes' },
      { id: 1, Icon: User, content: '10 Palentrantes' },
      { id: 2, Icon: User, content: '10 Registros' },
      { id: 3, Icon: User, content: '15 patrocinadores' },
    ],
  },
  {
    id: 3,
    urlVideo: 'https://www.youtube.com/embed/oZMH6vbfkFY?si=0fjlR625Ii6GcSFf',
    date: '15 a 17 de Março de 2024',
    Icon: CalendarBlank,
    title: 'Software Engineering Principles',
    details: [
      { id: 0, Icon: User, content: '+37 Participantes' },
      { id: 1, Icon: User, content: '10 Palentrantes' },
      { id: 2, Icon: User, content: '10 Registros' },
      { id: 3, Icon: User, content: '15 patrocinadores' },
    ],
  },
  {
    id: 4,
    urlVideo: 'https://www.youtube.com/embed/oZMH6vbfkFY?si=0fjlR625Ii6GcSFf',
    date: '15 a 17 de Março de 2024',
    Icon: CalendarBlank,
    title: 'Software Engineering Principles',
    details: [
      { id: 0, Icon: User, content: '+37 Participantes' },
      { id: 1, Icon: User, content: '10 Palentrantes' },
      { id: 2, Icon: User, content: '10 Registros' },
      { id: 3, Icon: User, content: '15 patrocinadores' },
    ],
  },
]
